#!/usr/bin/env python

from __future__ import print_function
from time import sleep
import ezsocket

sleep(2)

for i in range(0, 1000):
    socket = ezsocket.Socket('localhost', 5555)
    socket.send('{"put": [1, %s]}' % i)
    print(socket.receive(), end='')
    socket.close()
    sleep(2)
