#!/usr/bin/env python

from __future__ import print_function
from time import sleep
import easy_tcp

sleep(2)

for i in range(0, 1000):
    with easy_tcp.Socket('localhost', 5555) as socket:
        socket.send('{"put": [1, %s]}' % i)
        print(socket.receive())
    sleep(2)
