#!/usr/bin/env python

from __future__ import print_function
from time import sleep
import easy_tcp

sleep(2)

while True:
    socket = easy_tcp.Socket('localhost', 5555)
    socket.send('{"dump": [null, null]}')
    print(socket.receive())
    socket.close()
    sleep(5)
