#!/usr/bin/env python

from __future__ import print_function
from time import sleep
import json
import easy_tcp

sleep(2)

while True:
    with easy_tcp.Socket('localhost', 5555) as socket:
        socket.send(json.dumps({'dump': ['job', None]}))
        response = json.loads(socket.receive())
        print('%s jobs outstanding' % len(response['result']))
    sleep(5)
