#!/usr/bin/env python

from __future__ import print_function
from time import sleep
import easy_tcp

sleep(2)

while True:
    with easy_tcp.Socket('localhost', 5555) as socket:
        socket.send('{"get": [null, null]}')
        print(socket.receive())
    sleep(3)
